### ISSUE TITLE
darknet version with MacOS El Capitan

### ISSUE THREAD

**Issue by crazymxm** [philipperemy/yolo-9000#2]
It would be nice if you could offer the  darknet version with MacOS El Capitan,so we can run yolo9000 on our mac.

**Comment by philipperemy** [comment]
Thanks for reaching out @crazymxm ! Good news I can make it work without you to download anything!

The latest version of `darknet` seems to yield a Segmentation Fault on OSX El Capitan.

I could make it work that way:
```
git clone --recursive git@github.com:philipperemy/yolo-9000.git
cd yolo-9000
cat yolo9000-weights/x* > yolo9000-weights/yolo9000.weights # it was generated from split -b 95m yolo9000.weights
md5sum yolo9000-weights/yolo9000.weights # d74ee8d5909f3b7446e9b350b4dd0f44  yolo9000.weights
cd darknet
git reset --hard b61bcf544e8dbcbd2e978ca6a716fa96b37df767
make # Will run on CPU. For GPU support, scroll down!
./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/horses.jpg
```

The only difference here is this line:
```
git reset --hard b61bcf544e8dbcbd2e978ca6a716fa96b37df767
```

I explicitly ask for this commit because I know that it was working. 

What we can do (later on) is to investigate which commit triggers this segmentation fault.
