### ISSUE TITLE
remove object label

### ISSUE THREAD

**Issue by arjunfzk** [philipperemy/yolo-9000#22]
What if i want to remove some objects from the 9000 labels ?how do i do it? I tried editing the label txt file but it gives segmentation error.

**Comment by philipperemy** [comment]
@arjunfzk I think it's a bit more complex than that.

You should probably look at links like this one: https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/

**Comment by kulkarnikeerti** [comment]
@philipperemy the above link shows how the data is created for yolov2 followed by training the same model but there is no information on how the data is created for yolo9000 in a tree structure. Since its very different from other yolo models its quite difficult to understand the input preparation and how its used for further training. It would be great if you could you guide me to some useful articles?  Thanks in advance.
